version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "JeuFore"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "JeuFore"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"